
server:
    port: 8080

spring:
    application: 
        name: Login-system-api
    
    datasource: 
        url: jdbc:mysql://localhost:3306/loginsystemdb
        username: root
        password: root123
        driver-class-name: com.mysql.cj.jdbc.Driver
    
    jpa: 
        hibernate: 
            ddl-auto: update